#!/sbin/sh

EXP_KERNEL_VER="Linux localhost 2.6.32.9-00003-gb6084d9 #2 SMP PREEMPT Wed Jun 15 14:51:11 EDT 2"

DET_KERNEL_VER="$(uname -a)"

if [ "${DET_KERNEL_VER}" == "${EXP_KERNEL_VER}" ] ; then
    exit 0
else
    exit 1
fi
